### ISSUE TITLE
Hi,Is this code supported mouse event?

### ISSUE THREAD

**Issue by houxieyu** [deyihu/maptalks-echarts-gl#1]
I want get the building object which mouse over on or click.But the echarts.on('click') seems dont work,and the maptalks component's on('click') only get the mouse coordinates.How do I get the object name or id?

**Comment by houxieyu** [comment]
Add,I use  map3D series.and the echarts onclick dont work.I copy the code from your example on echarts gallary.link is http://gallery.echartsjs.com/editor.html?c=xBJpt1AN3f

**Comment by houxieyu** [comment]
Add,I'm very surprised by your code ,Its very effective on render a large mount of objects  rather than echarts-gl'mapbox code.It's very excellent.I wish use your component along in my project on future.

**Comment by deyihu** [comment]
@houxieyu 感谢你的issue  

我看了一下 Echart-GL 对事件支持这块是有问题的，因为这个插件的交互这块是由Echart-GL来处理

所有这个插件对事件的支持也是有问题的，正如你描述的那样

另外 Echarts-GL原生支持maptalks组件的  https://github.com/ecomfe/echarts-gl/commit/8a83d6211a50148e442afcbc41b4d7c347406616


建议你去 Echarts-GL的官方提个issue   https://github.com/ecomfe/echarts-gl

如果 你很急的用这个功能的话，我倒是有一个解决方案，就是捕获地图的点击的经纬度，然后利用该经纬度进行空间查询，房屋本质是Polygon ，可以利用Polygon的contains（lnglat）方法，从而判断该点落在哪个房屋上，从而达到你的目的，不过这不是最好的方法，当然这个问题我会仔细的看看和研究一下，当时没有注意这个问题

**Comment by deyihu** [comment]
@houxieyu  我测试了这个  http://gallery.echartsjs.com/editor.html?c=xBJ33yLImM&v=4

这个好像是可以的，至于buildings 的那个我在看看和研究一下是是么问题

**Comment by houxieyu** [comment]
Thank you.I find a maptalks3D component in echarts-gl source code,I would test this component.But I dont think it is perfect.And I'm looking forward your work yet.
This issue can be closed,thank you again.
